### ISSUE TITLE
Do not be saved in the Downloads automatically, and let specify name

### ISSUE THREAD

**Issue by dimitriskomnos** [JRCSTU/co2wui#112]
Do not save automatically the below files in the Downloads: 
- [x] ~log.txt file,~ taken from #110 
- [x] ~input template,~ taken from #111 
- [x] ~datasync template,~  taken from #98 

Also for the datasync files that you download: 
- [ ] Let user specify name, or default to be the cycle name? Like `nedc.automatic`, `nedc.manual`, `wltp.class3b` etc., taken from #112

**Comment by dimitriskomnos** [comment]
And this is my chrome setup: 

![image](https://user-images.githubusercontent.com/22169206/64857704-9432c500-d625-11e9-9886-2e9449c6f88f.png)

**Comment by stefanocorsi** [comment]
Strange, it works for me.
Have you tried to close and reopen Chrome after changing the option?
Could you try with FF as well?

**Comment by ankostis** [comment]
This doesn't seem like a co2wui issue, webserver has no control on the folder, just on the filename.
Do you see this issue with other sites?

**Comment by dimitriskomnos** [comment]
I do not download **.xlsx** files regularly, 
mostly **.pdf**, and there it works. 

But I tested now to download a **.xlsx** file from github, 
and actually it has the same behavior...
So it must be my problem or chrome's problem, 
because I dont think that there is another option for me to select.. 
This option I have it for long time now. 

@stefanocorsi did you try in chrome and did it work? 
I 'll try at my laptop at home as well, but if you want, please close the issue.

**Comment by dimitriskomnos** [comment]
ok, it was my mistake, and I am sorry for your time. 

At the end I had to _clear_ the option to open certain files autromatically....
![image](https://user-images.githubusercontent.com/22169206/64862732-8dab4a00-d633-11e9-910c-24522844cab0.png)

Now it works fine. 
![image](https://user-images.githubusercontent.com/22169206/64862709-7ff5c480-d633-11e9-9c32-bede27ab8250.png)

**Comment by dimitriskomnos** [comment]
The only remaining, which actually it is not a big thing is the automatic naming of the datasync files, 
which actually was not the case neither in old co2mpas. 

I close the issue
